/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qsatalk_JniLoad */

#ifndef _Included_com_qsatalk_cinjava
#define _Included_com_qsatalk_cinjava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qsatalk_Call
 * Method:    sendHello
 * Signature: ()Ljava/lang/String;
 */

JNIEXPORT jstring JNICALL native_sendHello
        (JNIEnv *, jobject);

/*
 * Class:     com_qsatalk_JniLoad
 * Method:    SayHelloInC
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */

JNIEXPORT jstring JNICALL native_SayHelloInC
        (JNIEnv *, jobject, jstring);
#else
extern JNIEXPORT jstring JNICALL native_sendHello
  (JNIEnv *, jobject);
extern JNIEXPORT jstring JNICALL native_SayHelloInC
  (JNIEnv *, jobject, jstring);
#endif
#ifdef __cplusplus
}
#endif
