/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qsatalk_JniLoad */

#ifndef _Included_com_qsatalk_javainc
#define _Included_com_qsatalk_javainc
#ifdef __cplusplus
extern "C" {
#endif

#else

#endif
#ifdef __cplusplus
}
#endif
