/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qsaserial_jniserialLoad */

#ifndef _Included_com_qsaserial
#define _Included_com_qsaserial
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qsaserial_jniserialLoad
 * Method:    init_serial_qsa
 * Signature: ()Ljava/lang/String;
 */

JNIEXPORT jstring JNICALL native_init_serial_qsa
        (JNIEnv *, jobject);
#else
extern JNIEXPORT jstring JNICALL native_init_serial_qsa
        (JNIEnv *, jobject);
#endif
#ifdef __cplusplus
}
#endif
